"""Rotas operacionais dos módulos da clínica."""
from edge_app import application as app_module

relatorios = app_module.relatorios
encaminhamentos = app_module.encaminhamentos
encaminhamento_especialista = app_module.encaminhamento_especialista
encaminhamento_especialista_gerar = app_module.encaminhamento_especialista_gerar
renumerador = app_module.renumerador
esocial = app_module.esocial
laudo_pcd = app_module.laudo_pcd
laudo_pcd_gerar = app_module.laudo_pcd_gerar
atestado_medico = app_module.atestado_medico
atestado_medico_gerar = app_module.atestado_medico_gerar
laudo_pcd_adicionar_empresa_rapido = app_module.laudo_pcd_adicionar_empresa_rapido
laudo_pcd_adicionar_cargo_rapido = app_module.laudo_pcd_adicionar_cargo_rapido
esocial_abas_base = app_module.esocial_abas_base
esocial_processar = app_module.esocial_processar
relatorios_async = app_module.relatorios_async
encaminhamentos_async = app_module.encaminhamentos_async
esocial_processar_async = app_module.esocial_processar_async
encaminhamento_especialista_cadastros = app_module.encaminhamento_especialista_cadastros
encaminhamento_especialista_add_empresa = app_module.encaminhamento_especialista_add_empresa
encaminhamento_especialista_add_especialista = app_module.encaminhamento_especialista_add_especialista
encaminhamento_especialista_remover_cadastro = app_module.encaminhamento_especialista_remover_cadastro
